services:
  website:
    image: nginx:alpine
    ports:
      - 8082:80
    networks:
      - nginx-proxy-network
    restart: unless-stopped
    volumes:
      - /var/lib/docker/volumes/portainer_data/_data/compose/7/website:/usr/share/nginx/html


networks:
  nginx-proxy-network:
    external: true
